require "rake/testtask"

Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["**/*_test.rb"]
  # doing this because sorbet dumps a ton of warnings
  t.verbose = false
  t.warning = false
end

task :typecheck do
  sh "srb tc"
end

task :default => [:typecheck, :test]
